### PR TITLE
regression tests

### LINKED ISSUE #1: Regression Tests
Dear All,

**Issue**
This code plugin should contain tests for detecting and avoiding regressions. We should therefore add testing capabilities.

**Proposed Solution**
Moose offers testing capabilities which could be also used within this code plugin. The tests are usually started with a script named ./run_tests while the tests itself are located in a folder structure named test/tests/....

Jörg

### PR DESCRIPTION
**Pull request by jmeier**
This code plugin should contain tests for detecting and avoiding regressions. We should therefore add testing capabilities.

Moose offers testing capabilities which could be also used within this code plugin. The tests are usually started with a script named ./run_tests while the tests itself are located in a folder structure named test/tests/....

This PR adds this functionality

closes #1

### CODE REVIEW

**Comment by jmeier** [comment]
Dear @Kavan-Khaledi, I've added one test. That one is a bit heavy. We should change that later.

File: include/DesaiHardeningStressUpdate.h [hunk 1]
```diff
@@ -4,7 +4,7 @@
 #pragma once
 
 #include "MultiParameterPlasticityStressUpdate.h"
-#include "TensorMechanicsHardeningModel.h"
+// #include "TensorMechanicsHardeningModel.h"
```
Comment (Kavan-Khaledi) [inline include/DesaiHardeningStressUpdate.h:7]: Could you please change this to "SolidMechanicsHardeningModel.h"

**Review by Kavan-Khaledi — APPROVED** [review]
